
remote_theme: nickbalestra/kactus

name: "Christoph Rieke"
description: "Geospatial Data Scientist"
meta_description: "Christoph Rieke's website"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 50
domain_name: 'http://chrieke.github.io'
google_analytics: 'UA-128373902-1'
disqus: false

# Details for the RSS feed generator
url:            'http://chrieke.github.io'
author:         'Christoph Rieke'
authorTwitter:  'chrieke'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
